// <auto-generated />
using System;
using App.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("App.Entities.DetallePlanillaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bonificaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentarios")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Deducciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpleadoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasExtra")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanillaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PlanillaId");

                    b.ToTable("DetallesPlanilla");
                });

            modelBuilder.Entity("App.Entities.EmpleadosEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PuestoTrabajo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("App.Entities.PlanillaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Planillas");
                });

            modelBuilder.Entity("App.Entities.DetallePlanillaEntity", b =>
                {
                    b.HasOne("App.Entities.EmpleadosEntity", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("App.Entities.PlanillaEntity", "Planilla")
                        .WithMany()
                        .HasForeignKey("PlanillaId");

                    b.Navigation("Empleado");

                    b.Navigation("Planilla");
                });
#pragma warning restore 612, 618
        }
    }
}
